name: pww3
dependencies:
  - python=3.10.13
  - numpy
  - streamlit
  - conda-forge::mordred
  - conda-forge::rdkit
  - pip
  - pip:
    - rdkit
    - mordred
    - python-javabridge
    - python-weka-wrapper3
